name: SwiftPay CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Transaction Gateway
        run: mvn clean package -DskipTests
        working-directory: transaction-gateway

      - name: Build Ledger Service
        run: mvn clean package -DskipTests
        working-directory: ledger-service

      - name: Build Analytics Worker
        run: mvn clean package -DskipTests
        working-directory: analytics-worker